### ISSUE TITLE
[1.20.4][Fabric] Minecraft crashes when trying to open the config via modmenu

### ISSUE THREAD

**Issue by etoGitHubDeniski** [Team-Resourceful/Resouceful-Config#16]
### Bug Description

I added Resourceful-Config as Ad Astra dependency. And when I try to open the config of these two mods in minecraft, Minecraft has a fatal error. I can't know for sure, but I think the reason is modmenu.

### How to Reproduce?

1. Start Minecraft 1.20.4 with mods
2. Open mod list (modmenu 9.0.0)
3. Try click to ResourcefulConfig (2.4.4) config button

### Expected Behavior

Minecraft has crash

### Version

1.20.4

### Mod Loader Version

0.96.1

### Mod Loader

Fabric

### Logs or additional context

[00:10:52] [Render thread/ERROR]: Invalid mod icon for icon source resourcefulconfig: icon.png
java.nio.file.NoSuchFileException: /icon.png
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:861)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.newInputStream(ZipPath.java:749)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:261)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at com.terraformersmc.modmenu.util.mod.fabric.FabricIconHandler.createIcon(FabricIconHandler.java:34)
	at com.terraformersmc.modmenu.util.mod.fabric.FabricMod.getIcon(FabricMod.java:161)
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.getIconTexture(ModListEntry.java:131)
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:339)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$245(class_757.java)
	at net.minecraft.class_757.wrapOperation$boi000$fabric-screen-api-v1$onRenderScreen(class_757.java:2611)
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

[00:12:59] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.class_310.method_1523(class_310.java:1352)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.AbstractMethodError: Receiver class com.teamresourceful.resourcefulconfig.client.components.configs.ConfigHeaderItem does not define or inherit an implementation of the resolved method 'abstract void setWidth(int)' of interface com.teamresourceful.resourcefulconfig.client.components.base.ListWidget$Item.
	at com.teamresourceful.resourcefulconfig.client.components.base.ListWidget.updateLastHeight(ListWidget.java:137)
	at com.teamresourceful.resourcefulconfig.client.components.base.ListWidget.add(ListWidget.java:43)
	at com.teamresourceful.resourcefulconfig.client.ConfigsScreen.method_25426(ConfigsScreen.java:47)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1187)
	at com.terraformersmc.modmenu.gui.ModsScreen.lambda$init$4(ModsScreen.java:193)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	... 14 more

[00:12:48] [Render thread/INFO]: emissive suffixes loaded: {_e}.
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-02-15 00:12:11
Description: mouseClicked event handler

java.lang.AbstractMethodError: Receiver class com.teamresourceful.resourcefulconfig.client.components.configs.ConfigHeaderItem does not define or inherit an implementation of the resolved method 'abstract void setWidth(int)' of interface com.teamresourceful.resourcefulconfig.client.components.base.ListWidget$Item.
	at com.teamresourceful.resourcefulconfig.client.components.base.ListWidget.updateLastHeight(ListWidget.java:137)
	at com.teamresourceful.resourcefulconfig.client.components.base.ListWidget.add(ListWidget.java:43)
	at com.teamresourceful.resourcefulconfig.client.ConfigsScreen.method_25426(ConfigsScreen.java:47)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1187)
	at com.terraformersmc.modmenu.gui.ModsScreen.lambda$init$4(ModsScreen.java:193)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.class_310.method_1523(class_310.java:1352)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.teamresourceful.resourcefulconfig.client.components.base.ListWidget.updateLastHeight(ListWidget.java:137)
	at com.teamresourceful.resourcefulconfig.client.components.base.ListWidget.add(ListWidget.java:43)
	at com.teamresourceful.resourcefulconfig.client.ConfigsScreen.method_25426(ConfigsScreen.java:47)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1187)
	at com.terraformersmc.modmenu.gui.ModsScreen.lambda$init$4(ModsScreen.java:193)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)

-- Affected screen --
Details:
	Screen name: com.terraformersmc.modmenu.gui.ModsScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.class_310.method_1523(class_310.java:1352)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 8714.148s
	Wall uptime: 8700.695s
	High-res time: 8684.175s
	Client ticks: 171317 ticks / 8565.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 3
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, ad_astra, advancementplaques, appleskin, bclib, betteradvancements, betterend, betterf3, betternether, blur, bobby, caffeineconfig, cloth-config, cristellib, ctov, dark-loading-screen, entity_model_features, entity_texture_features, entityculling, expanded_ecosphere, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, inventoryprofilesnext, iris, jade, libipn, make_bubbles_pop, maptooltip, midnightlib, modmenu, nvidium, realisticsleep, reeses-sodium-options, resourcefulconfig, roughlyenoughitems, satin, simple-snowy-fix, skinlayers3d, sodium, sodium-extra, team_reborn_energy, file/BACAP Language Pack 1.16.0.2.zip, file/Default-Dark-Mode-1.20.2+-2023.11.0.zip, file/EmbellishedStone-1.20.1-1.0.0.zip, file/VanillaEvolved_1.5.0.zip, file/Rethoughted Trident 1.20.3 - 1.20.4.zip, file/FreshAnimations_v1.8.1.zip, file/FA+All_Extensions-v1.2.zip

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4265589784 bytes (4067 MiB) / 10099884032 bytes (9632 MiB) up to 10099884032 bytes (9632 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2520
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4665
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x1638
	Graphics card #1 versionInfo: DriverVersion=27.20.21020.5007
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 53535.03
	Virtual memory used (MB): 33964.36
	Swap memory total (MB): 37818.72
	Swap memory used (MB): 13685.70
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9632M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ad_astra: Ad Astra 1.16.4
			javazoom_jlayer: jlayer 1.0.1
		advancementplaques: Advancement Plaques 1.5.1
		appleskin: AppleSkin 2.5.1+mc1.20.3
		architectury: Architectury 11.0.12
		bclib: BCLib 3.30.1
			wunderlib: WunderLib 1.30.0
		betteradvancements: Better Advancements 0.4.0.176
		betterend: Better End 4.30.1
		betterf3: BetterF3 9.0.0
		betternether: Better Nether 9.30.0
		blur: Blur (Fabric) 3.2.0
			midnightlib: MidnightLib 1.5.3
			satin: Satin 1.15.0
		bobby: Bobby 5.1.0+mc1.20.4
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		botarium: Botarium 3.0.7
			team_reborn_energy: Energy 3.0.0
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		cristellib: Cristel Lib 1.2.4
			blue_endless_jankson: jankson 1.2.3
		ctov: ChoiceTheorem's Overhauled Village 3.4.2
		customskinloader: CustomSkinLoader 14.19.1
		dark-loading-screen: Dark Loading Screen 1.6.14
		entity_model_features: Entity Model Features 1.2.3
		entity_texture_features: Entity Texture Features 5.2.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.3.1
		expanded_ecosphere: Expanded Ecosphere 3.3.1
		fabric-api: Fabric API 0.96.1+1.20.4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.13+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.1+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.1+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.23+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.7+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.63+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.11+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.0+d74054c14f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.10+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		forgeconfigapiport: Forge Config API Port 20.4.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		iceberg: Iceberg 1.1.18
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 13.3.0
		java: OpenJDK 64-Bit Server VM 17
		leavesbegone: Leaves Be Gone 20.4.1
		libipn: libIPN 4.0.1
		lithostitched: Lithostitched 1.1.5
		make_bubbles_pop: Make Bubbles Pop Mod 0.2.0-fabric
		maptooltip: Map Tooltip 3.0.0
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.0.0
		mousetweaks: Mouse Tweaks 2.25
		nvidium: Nvidium 0.2.6-beta
		puzzleslib: Puzzles Lib 20.4.22
		realisticsleep: Realistic Sleep 1.10.2+mc1.20.3-1.20.4
			server_translations_api: Server Translations API 2.2.0+1.20.3-rc1
				packet_tweaker: Packet Tweaker 0.5.0+1.20.2-rc1
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.4-build.102
		resourcefulconfig: Resourcefulconfig 2.4.4
		resourcefullib: Resourceful Lib 2.4.7
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		roughlyenoughitems: Roughly Enough Items 14.0.688
			error_notifier: Error Notifier 1.0.9
		simple-snowy-fix: Simple Snowy Fix 1.0.0
		skinlayers3d: 3d-Skin-Layers 1.6.2
		sodium: Sodium 0.5.8+mc1.20.4
		sodium-extra: Sodium Extra 0.5.4+mc1.20.4-build.116
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		t_and_t: Towns and Towers 1.12.0
	Loaded Shaderpack: ComplementaryReimagined_r5.1.1.zip
		Profile: HIGH (+7 options changed by user)
	Launched Version: 1.20.4 Fabric Denis
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.65, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, ad_astra, advancementplaques, appleskin (incompatible), bclib, betteradvancements (incompatible), betterend, betterf3, betternether, blur, bobby, caffeineconfig, cloth-config, cristellib, ctov (incompatible), dark-loading-screen, entity_model_features, entity_texture_features, entityculling, expanded_ecosphere, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, inventoryprofilesnext, iris, jade (incompatible), libipn, make_bubbles_pop, maptooltip (incompatible), midnightlib, modmenu, nvidium, realisticsleep, reeses-sodium-options, resourcefulconfig, roughlyenoughitems, satin, simple-snowy-fix, skinlayers3d, sodium, sodium-extra, team_reborn_energy, file/BACAP Language Pack 1.16.0.2.zip, file/Default-Dark-Mode-1.20.2+-2023.11.0.zip, file/EmbellishedStone-1.20.1-1.0.0.zip (incompatible), file/VanillaEvolved_1.5.0.zip, file/Rethoughted Trident 1.20.3 - 1.20.4.zip, file/FreshAnimations_v1.8.1.zip (incompatible), file/FA+All_Extensions-v1.2.zip (incompatible)
	Current Language: ru_ru
	Locale: ru_RU
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics

**Comment by ThatGravyBoat** [comment]
Fixed in 2.4.5
